Feat: 프로젝트 URL 입력 페이지 구현  및 버전 컴포넌트 추가
Figci/Figci-Plugin-Client pull request #11
Opened 2024-02-18 15:37 UTC by doitchuu

## Fix (이슈 번호)
closes #10 

<br />

## 해결하려던 문제를 알려주세요!
온보딩 이후, 사용자가 로그인을 성공하면 프로젝트 URL 입력 화면을 띄웁니다.
URL 유효성 검사를 성공하면, Client Storage 내 토큰을 받아 서버에 버전 히스토리 데이터 요청을 보냅니다.
요청을 성공적으로 받으면 버전 선택 페이지로 이동합니다.

<br />

## 어떻게 해결했나요?

### ClientStorage onmessage 오류 관련

`onmessage`가 제대로 실행되지 않아서 토큰값이 계속 같은 값으로 서버에 요청이 가고 있었습니다.
원인은` figma.ui.onmessage`를 따로 함수로 선언했던 게 원인이었습니다.

`onmessage` 핸들러를 두 번 사용하면 안 되는 주된 이유는 JavaScript에서 이벤트 핸들러를 직접 할당하는 방식 (element.onEvent = handler)은 기존에 할당된 핸들러를 새로 할당된 핸들러로 덮어쓰기 때문이라는 걸 알게되었습니다.

첫 번째로 할당된 `onmessage` 핸들러는 두 번째 핸들러에 의해 제거됩니다. 
따라서 첫 번째 핸들러에 정의된 로직은 더 이상 실행되지 않습니다.

```javascript
figma.showUI(__html__, { width: 400, height: 540 });

figma.ui.onmessage = async message => {
  console.log(message);

  if (message.type === "SAVE_ACCESS_TOKEN") {
    console.log("톡큰", message.content);
    await figma.clientStorage.setAsync("accessToken", message.content);
  }
};

figma.ui.onmessage = async message => {
  if (message.type === "GET_ACCESS_TOKEN") {
    const accessToken = await figma.clientStorage.getAsync("accessToken");

    figma.ui.postMessage({
      type: "GET_ACCESS_TOKEN",
      content: accessToken,
    });
  }
};
``` 

<br />

그래서 변경한 로직은 아래와 같습니다.
모든 이벤트 처리 로직을 하나의 `onmessage` 핸들러 내에 포함시키고, 
이벤트 타입에 따라 적절한 분기 처리를 하는 방식으로 진행해 중복으로 이벤트가
덮어쓰는 걸 방지하는 로직으로 변경했습니다.

```javascript
figma.showUI(__html__, { width: 400, height: 540 });

figma.ui.onmessage = async message => {
  if (message.type === "SAVE_ACCESS_TOKEN") {
    await figma.clientStorage.setAsync("accessToken", message.content);
  }

  if (message.type === "GET_ACCESS_TOKEN") {
    const accessToken = await figma.clientStorage.getAsync("accessToken");

    figma.ui.postMessage({
      type: "GET_ACCESS_TOKEN",
      content: accessToken,
    });
  }
};
``` 

<br />

[onmessage 중복 관련](https://basketdeveloper.tistory.com/80)
> 더 자세한 공식 문서로 변경하겠습니다.

<br />

## 우려사항이 있나요?(선택사항)

### 패키지 추가 설치 관련
nanoid를 이번에 설치하게 되어서 npm install로 꼭 install 해주세요!

```javascript
npm install
``` 

<br />

### 버전 선택 페이지 추가 작업 관련
현재 버전 선택 페이지 로직으로는 정적 컴포넌트 구현과 버전 정보 유효성 검사만 진행되어 있습니다.

서버에 선택된 버전들에 대해 공통 페이지를 요청하고, 현재 페이지 아이디와 비교하는 로직부터 진행되면 될 것 같습니다.
> 아래에 beforeDate, beforeVersion, afterDate, afterVersion을 찍은 콘솔입니다. 
> 서버에 요청을 보내고, 클라이언트에게 토큰을 요청하는 로직이 추가가 필요합니다.

<img width="659" alt="추가 구현 필요" src="https://github.com/Figci/Figci-Plugin-Client/assets/43771772/f9c94263-6bc7-4bdd-af67-c892bdc7e913">

<br />

### 토스트 팝업 위치 버그 관련
웹 내에서도 왼쪽으로 토스트 팝업이 치우치고 있는데 플러그인에서
해결한 방법 공유 드립니다. 추후 웹 클라이언트 작업 시, 추가로 반영 부탁 드립니다.

> 토스트 팝업이 오른쪽에서 나와서 중앙으로 가는 이유는 left: 50%;와 transform: translateX(-50%);가 함께 사용되어서 발생했습니다.
> margin을 0 auto로 설정하고, left, right를 0으로 설정. position을 fixed로 주어 해결했습니다.
> 사이즈는 웹사이즈로 그대로 사용하시면 됩니다!(폰트, 외관 크기 등)

```javascript
const Toast = styled.div`
  position: fixed;
  z-index: 2;
  top: 85%;
  left: 0;
  right: 0;
  margin: 0 auto;

  display: flex;
  justify-content: center;
  align-items: center;
  width: 80%;
  height: 44px;
  border-radius: 8px;

  animation: ${fadeInUp} 0.5s ease-in-out;

  opacity: 0.8;
  background-color: #000000;
  color: #ffffff;
  font-family: "Noto Sans KR";
  font-size: 0.75rem;
  text-align: center;
  font-weight: 700;
`;

export default ToastPopup;
``` 

<br />

## 잠깐! 확인해보셨나요?

- [X]  셀프 리뷰는 완료하셨나요?
- [X]  가장 최신 브랜치를 pull했나요?
- [X]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [X]  코드 컨벤션을 모두 지켰나요?
- [X]  적절한 라벨이 있나요?
- [X]  assignee가 있나요?

<br />

## Attachment(선택사항) 
### URL 입력 페이지(+ 토스트 팝업)
<img width="402" alt="URL 입력 페이지" src="https://github.com/Figci/Figci-Plugin-Client/assets/43771772/9bffa14b-2efd-4f54-aabc-5c5a8c599371">
<img width="399" alt="토스트팝업" src="https://github.com/Figci/Figci-Plugin-Client/assets/43771772/08f6ba15-2bbe-4039-8d55-73f7351a964f">

### 버전 선택 페이지
<img width="397" alt="버전 선택 페이지" src="https://github.com/Figci/Figci-Plugin-Client/assets/43771772/33bb8b05-66a0-4681-87dd-d6ba7688d228">

<br />

2024-02-18 16:26 UTC, tjd985 requested changes
코멘트 확인 부탁드립니다!

2024-02-18 16:26 UTC, tjd985 commented on package.json
> +    "nanoid": "^5.0.5",
`nanoid`추가!
확인했습니다~

2024-02-18 16:26 UTC, tjd985 commented on src/plugin/code.js
> +  }
1개의 `onMessage`에서 `type`에 따라 분기처리를 해주어서 해결하셨다고 했던
`PR`에서 말씀하신 그부분 이군요! 👍

2024-02-18 16:26 UTC, tjd985 commented on src/ui/components/Header/index.jsx
> +      </Link>
`navigate`로도 동일한 요청을 처리할 수 있지만
별다른 로직 처리가 없어서 `useNavigate`를 사용하지 않고, `Link`처리 해주시점에서
목적에 맞게 사용하신 것 같아서 좋네요! 💯

2024-02-18 16:26 UTC, tjd985 commented on src/ui/components/NewProject/index.jsx
> +import postMessage from "../../../utils/postMessage";
- `P1`
```suggestion
import useProjectStore from "../../../store/project";
import useProjectVersionStore from "../../../store/projectVersion";

import getProjectKeyFromURI from "../../../utils/getProjectKeyfromURI";
import isValidFigmaUrl from "../../../utils/isValidFigmaUrl";
import postMessage from "../../../utils/postMessage";
import getAllVersions from "../../../service/getAllVersions";
```

`store import`구문에서 한줄 개행 해주시고, `utils` 끼리 묶어서 작성하면 더욱 가독성이 좋을 것 같습니다!

2024-02-18 16:26 UTC, tjd985 commented on src/ui/components/NewProject/index.jsx
> +  }, [inputValue]);
window에 `handleMessage`를 처음 달아주었을 때, `클로저`로 인해 `inputValue`의 초깃값을 기억하게 되는데
`useEffect`에 `dependency`를 `inputValue를` 넣어줌으로 써 리렌더링 될때마다 새로운 `inputValue`를 참조하도록 처리하셨네요! 👍

2024-02-18 16:26 UTC, tjd985 commented on src/ui/components/NewProject/index.jsx
> +  };
- `P2`
`inputValue`를 따로 선언하지 않고
```suggestion
  const handleChangeInput = ev => {
    setProject({ projectUrl: ev.target.value });
  };
```
이렇게 작성하는것도 가능하지 않을까요?

```js
useEffect(() => {
    window.addEventListener("message", handleMessage);

    return () => {
      window.removeEventListener("message", handleMessage);
    };
  }, [project.projectUrl]);
```

혹시 제한되는 부분이 있는지 궁금합니다!

2024-02-18 16:26 UTC, tjd985 commented on src/ui/components/NewProject/index.jsx
> +          </div>
- `P1`
`<div className="buttons"></div>` 는 스타일이 따로 적용이 되어져 있지 않은 것 같습니다!
`div`태그로 버튼을 한번 감싸준 이유가 있으신가요?

2024-02-18 16:26 UTC, tjd985 commented on src/ui/components/NewProject/index.jsx
> +  }
- `P1`
`description`은 존재하지 않는 클래스이름 인것 같습니다!

2024-02-18 16:26 UTC, tjd985 commented on src/ui/components/ProjectVersion/index.jsx
> +    );
- `P2`
`handleClick`함수 내에 너무 많은 로직이 집중되어져 있는것 같아요!
모듈화를 할 수 있는 함수들이 있다면(`validate` 등등) 모듈화를 하면 가독성이 더욱 좋아질 것 같습니다!

2024-02-18 16:26 UTC, tjd985 commented on src/ui/components/ProjectVersion/index.jsx
> +  }
그리드를 사용하셨네요! 💯

2024-02-18 16:26 UTC, tjd985 commented on src/ui/components/ProjectVersion/index.jsx
> +            </p>
- `P2`
공통 컴포넌트 `Description`을 활용해보시면 어떨까요?!

2024-02-18 16:26 UTC, tjd985 commented on src/utils/getLastVersion.js
> +export default getLastVersion;
가장 최근 버전을 가져오는 로직을 모듈화 해주셔서
컴포넌트 내 비즈니스 로직이 줄어들은 덕에 가독성이 향상된 것 같습니다! 👍

2024-02-18 16:26 UTC, tjd985 commented on src/utils/postMessage.js
> +const postMessage = (type, content = null, origin = "*") => {
기본값을 `null`로 지정해줌으로 써
`undefined`대신 `null`이 들어감에 따라 조금더 명확한 코드가 되었네요! 👍

2024-02-18 17:44 UTC, doitchuu reviewed
리뷰 확인 후 반영했습니다 👍

2024-02-18 17:44 UTC, doitchuu commented on src/ui/components/NewProject/index.jsx
> +import postMessage from "../../../utils/postMessage";
네 반영하겠습니다! 👍

2024-02-18 17:44 UTC, doitchuu commented on src/ui/components/NewProject/index.jsx
> +  };
지역 상태로 관리하는 게 주니 좋네요! 테스트했을 때 문제 없이 버전 선택까지 넘어가네요 :)

글로벌 상태를 바로 쓸 생각을 못했는데 예리하게 짚어주셔서 감사합니다!
반영해두겠습니다! 👍

2024-02-18 17:44 UTC, doitchuu commented on src/ui/components/NewProject/index.jsx
> +          </div>
해당 부분 불필요하다 판단되어 반영해두었습니다 😂

2024-02-18 17:44 UTC, doitchuu commented on src/ui/components/NewProject/index.jsx
> +  }
네! 수정하곘습니다. CSS 코드들도 꼼꼼히 보겠습니다 😂

2024-02-19 01:40 UTC, kyeongjun-ko commented on src/plugin/code.js
> +  if (message.type === "GET_ACCESS_TOKEN") {
P3: 사용자 인증 코드와 state로 토큰을 요청하는 로직이군요

2024-02-19 04:14 UTC, kyeongjun-ko commented on src/service/getAllVersions.js
> +  const responseResult = await response.json();
P3: responseResult 는 결과와 응답이라는 두개의 의미가 중첩되어서
Json 으로 바뀐 데이터 라는것을  명시적인 측면에서
`responseJson` 또는 `resultJson` 도 쓸수 있을것 같습니다.

2024-02-19 04:34 UTC, kyeongjun-ko commented on src/utils/isValidFigmaUrl.js
> +const isValidFigmaUrl = figmaUrl => {
P3: 입력한 피그마 URL 유효성 검증 로직을 재사용하셨군요 좋습니다.

2024-02-19 04:36 UTC, kyeongjun-ko commented on src/ui/components/ProjectVersion/index.jsx
> +    clearProjectVersion();
P3: 버전 페이지에 왔을때 ProjectVersion 을 reset 하늘 부분
로직 흐름 이해가 부족해서 조금 설명해주시면 감사하겠습니다.

2024-02-19 04:55 UTC, kyeongjun-ko commented on src/ui/components/ProjectVersion/index.jsx
> +    if (ev.target.classList.contains("prev")) {
P3: 이전, 이후 버튼 클릭이벤트 핸들러 함수의 분기처리를 해주셨군요
추후에 리팩터링으로 클래스명을 바꾸게 될텐데 그때 같이
로직도 수정해줘야 하기때문에 클래스명에 의존해서 
함수의 분기처리를 해주는것보다 따로 만들어도 좋을것 같습니다.

2024-02-19 04:59 UTC, kyeongjun-ko commented on src/ui/components/shared/Description.jsx
> +const StyledSpan = styled.span`
P3: styled component 여러가지 네이밍 컨벤션을 중에서
개인적으로 직관적이고 깔끔하다 생각한 방법에 대해 정리한 글입니다.
추후 리팩터링시 참고하면 좋을것 같습니다.

https://medium.com/inturn-eng/naming-styled-components-d7097950a245

2024-02-19 05:46 UTC, doitchuu commented on src/ui/components/ProjectVersion/index.jsx
> +    clearProjectVersion();
버전 재선택으로 버전 페이지를 다시 돌아왔을 때, 상태에 저장되어 있던 버전 상태들을 지우는 로직입니다 😀

2024-02-19 06:08 UTC, tjd985 approved these changes
확인했습니다!
고생하셨습니다!

2024-02-19 06:10 UTC, kyeongjun-ko approved these changes

2024-02-19 06:11 UTC, merged