Feature 변경 페이지 - 페이지네이션 구현
Figci/Figci-Plugin-Client pull request #32
Opened 2024-02-25 15:22 UTC by kyeongjun-ko

## Fix (이슈 번호)
None

<br />

## 해결하려던 문제를 알려주세요!

- 플러그인 변경 페이지 - 변경된 노드의 페이지네이션 기능 구현
 1. 버전 재선택 버튼 위치 및 스타일 변경 - 헤더바 고정
 2. 페이지네이션 정보 표시 - 현재 선택 변경 노드 / 전체 변경 노드 갯수

| 변경 전 | 변경 후 |
| ---- | ---- |
|![image](https://github.com/Figci/Figci-Plugin-Client/assets/95596243/d5c35318-1e80-491b-81fa-ceb1091e9f20)|![image](https://github.com/Figci/Figci-Plugin-Client/assets/95596243/87b05966-5305-4283-a152-c2abbea3bdc6)|

 4. 페이지네이션 버튼 클릭 시 다음 변경 노드 선택 후 화면 이동

   ![페이지네이션-변경노드중심](
https://github.com/Fig[ci/Figci-Plugin-Client/assets/95596243/2ce38ceb-095c-41eb-b9ad-7d0785f07592](https://github.com/Figci/Figci-Plugin-Client/assets/95596243/2ce38ceb-095c-41eb-b9ad-7d0785f07592)
)

 5. 페이지네이션 변경 결과 존재 여부에 따라 버튼 비활성화

   ![페이지네이션- 비교불가 비활성화](
https://github.com/Figci/Figci-Plugin-[Client/assets/95596243/fd8511cb-2101-443e-81b3-fbfba8613290](https://github.com/Figci/Figci-Plugin-Client/assets/95596243/fd8511cb-2101-443e-81b3-fbfba8613290)
)

 6. 변경 노드 렌더시 첫번째 변경 노드 포커스

   ![첫번째 노드포커스](
https://github.com/Figci/Figci-Plugin-Client/a[ssets/95596243/89932ff2-f81f-4af1-8b84-182ccaa4b829](https://github.com/Figci/Figci-Plugin-Client/assets/95596243/89932ff2-f81f-4af1-8b84-182ccaa4b829)
)

<br />

## 어떻게 해결했나요?

1. 이벤트에 따른 페이지네이션 정보 업데이트 주체가 달라진다.
 페이지가 변경 되었을때는 `클라이언트`에서 페이지네이션의 정보가 업데이트
 선택된 노드가 변경 되었을때는 `샌드박스`에서 페이지네이션의 정보가 업데이트

> 클라이언트에서 페이지네이션 업데이트

```
useEffect(() => {
    if (diffingResult.result === "error") {
     // 비교 결과 존재하지 않는 페이지인 경우
     setPagination({ result: false, frameCounts: "- / -" });
      return;
    }
     // 비교 결과 존재하는 페이지인 경우
     setPagination({ result: false, frameCounts: "- / -" });
    setPagination({
      result: true,
      currentCount: 0,
      frameCounts: Object.keys(differences).length,
    });
  }, [diffingResult]); // 변경 결과 상태 업데이트시 실행
```

> 서버에서 페이지네이션 업데이트

```
 // 선택된 노드 변경시 이벤트 발생
figma.on("selectionchange", () => {
  // 변경된 노드 갯수
  const totalFrameCount = differenceRectangleIdList.length;
 // 선택한 노드가 변경된 노드인 경우
  if (differenceRectangleIdList.includes(selectedNode.id)) {
    figma.ui.postMessage({
      type: "FRAME_PAGINATION",
      content: {
        result: true,
        currentCount: currentFrameIndex,
        frameCounts: totalFrameCount,
      },
    });
  } else {
    // 선택한 노드가 변경된 노드 아닌경우
    figma.ui.postMessage({
      type: "FRAME_PAGINATION",
      content: {
        result: true,
        currentCount: 0,
        frameCounts: totalFrameCount,
      },
    });
  }
});
```

2. 변경 결과 존재 여부에 따른 조건부 렌더링 - 버튼 비활성화
 활성화 된 버튼과 비활성화 된 버튼을 2개를 렌더하여서
 변경사항이 존재하는지 여부에 따라 분기 처리하여서 조건부 렌더링 된다.

```
// 페이지네이션 버튼 활성화 여부
const [isComparable, setIsComparable] = useState(false);
const isComparablePage = allPageIds.includes(pageId);
if (!isComparablePage) {
  setIsComparable(false);
}
setIsComparable(true);
// 변경 결과 존재 여부에 다른 조건부 렌더링
{isComparable ? (
// 활성화 버튼 렌더링
 ) : (
// 비활성화 버튼 렌더링
)}
```

4. postMessage 사이드 이펙트 처리
 버튼에서 발생하는 postMessage 메서드는 사이드 이펙트 처리를 해야한다.
 페이지네이션 버튼 클릭시 지역상태를 업데이트 하는 이벤트 핸들러 함수 작성
 useEffect 의존성으로 상태를 등록하여서 버튼 클릭시 `postMessage` 호출함.

```
const [isPaginationClicked, setIsPaginationClicked] = useState("");
useEffect(() => {
  if (isPaginationClicked.type === "prev") {
    postMessage("PREV_DIFFERENCE_RECTANGLE");
  }
  if (isPaginationClicked.type === "next") {
    postMessage("NEXT_DIFFERENCE_RECTANGLE");
  }
}, [isPaginationClicked]);
```

<br />

## 우려사항이 있나요?(선택사항)

1. URL입력 페이지 추가에 따른 글로벌 스토어로 부터 FileKey 수신 테스트 필요

<br />

## 잠깐! 확인해보셨나요?
- [x]  셀프 리뷰는 완료하셨나요?
- [x]  가장 최신 브랜치를 pull했나요?
- [x]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [x]  코드 컨벤션을 모두 지켰나요?
- [x]  적절한 라벨이 있나요?
- [x]  assignee가 있나요?

2024-02-25 16:50 UTC, tjd985 requested changes
코멘트 확인 부탁드립니다!

2024-02-25 16:50 UTC, tjd985 commented on src/plugin/code.js
> +  }
변경사항이 렌더링이 될 시 첫번째 노드로 자동 포커스 되게 하셨군요! 👍

2024-02-25 16:50 UTC, tjd985 commented on src/plugin/code.js
> +    const isSelectedNode = figma.currentPage.selection[0];
- `P1`
`boolean`값이 담기는 변수명을 보통 `is`로 시작하는 변수명으로 짓는데
코드상에서는 `boolean`값이 담기는 것 같지 않습니다!
변수명 수정 부탁드려요!

2024-02-25 16:50 UTC, tjd985 commented on src/plugin/code.js
> +        (currentNodeIndex - 1) % differenceRectangleIdList.length;
- `P3`
만약, `currentNodeIndex`가 0인 경우에는 `prevNodeIndex`가 `-1`이 될 것 같은데
혹시 이를 방지하기 위한 코드가 있을까요?

2024-02-25 16:50 UTC, tjd985 commented on src/plugin/code.js
> +    figma.notify(`이전 변경 사항이 선택 되었습니다.`);
- `P1`
이전버튼과 다음버튼을 눌렀을 때 로직이 거의 흡사한데, 각각 따로 구현이 되어져 있는 것 같습니다!
차이점은  `nextNodeIndex`를 구할 때 `currentNode`에서 `1을 빼주냐, 더해주냐` 의 차이만 있는 것 같은데요
로직을 하나로 합치고, 해당 부분만 분기처리를 해줌으로써 최대한 중복로직을 줄일 수 있지 않을까요?

2024-02-25 16:50 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +  }, [isPaginationClicked]);
- `P2`
```suggestion
  useEffect(() => {
    if (isPaginationClicked.type === "prev") {
      postMessage("PREV_DIFFERENCE_RECTANGLE");
      
      return;
    }

    postMessage("NEXT_DIFFERENCE_RECTANGLE");
  }, [isPaginationClicked]);
```

`prev`와 `next`만 있기 때문에 `if문`을 두개 써줄 필요가 없을 것 같습니다!

2024-02-25 16:50 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +      setIsComparable(true);
- `P1`
```suggestion
      setIsComparable(true);
```

2024-02-25 16:50 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +    postMessage("GET_PROJECT_KEY");
- `P1`
`"GET_PROJECT_KEY"`는 배포할때 문제가 되기때문에 `sandbox` 코드에서 삭제한걸로 알고있습니다!
수정 부탁드려요!

2024-02-25 16:50 UTC, tjd985 commented on src/ui/components/ProjectVersion/index.jsx
> +            frameCounts: Object.keys(diffingResult.content.differences).length,
- `P1`
`Differnece 컴포넌트`에서 해당 `frameCounts`는 사용되지 않는 것 같습니다!
삭제 부탁드려요!

2024-02-25 16:50 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +  }
- `P1`
CSS writing convention을 지켜주세요..🥲

2024-02-25 16:50 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +  const [isPaginationClicked, setIsPaginationClicked] = useState("");
- `P1`
```suggestion
  const [clickedType, setClickedType] = useState({});
```

1. 코드상에서 할당되는 값이 객체로 확인됩니다!
따라서 is로 시작하는 변수명은 부적절하다고 판단되네요!

2. 해당 state가 할당되는 type을 초깃값으로 설정해주면 해당 타입이 어떤 type을 값으로 갖게 되는지 유추 할 수 있게 되서 가독성에 도움이 될 것 같아요!
지금같은 상황에는 `빈 객체`가 초깃값으로 들어가면 좋을 것 같습니다!

2024-02-25 16:50 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +    }
- `P1`
중복코드가 존재합니다
```suggestion
    if (ev.data.pluginMessage.type === "FRAME_PAGINATION") {
      const framePagination = ev.data.pluginMessage.content;

      setPagination(framePagination);
    }
```

2024-02-25 16:50 UTC, tjd985 commented on src/plugin/code.js
> +    }
- `P2`
early return 패턴을 적용해보면 좋을 것 같습니다!
```suggestion
    if (totalFrameCount) {
      figma.ui.postMessage({
        type: "FRAME_PAGINATION",
        content: {
          result: true,
          currentCount: 0,
          frameCounts: totalFrameCount,
        },
      });
      
      return;
    }
    
    figma.ui.postMessage({
      type: "FRAME_PAGINATION",
      content: {
        result: false,
        frameCounts: "- / -",
      },
    });
```

2024-02-25 18:16 UTC, doitchuu requested changes
코멘트 확인 부탁드립니다. 추가 기능이라 구현하기 쉽지 않으셨을텐데 고생 많으셨습니다 👍

2024-02-25 18:16 UTC, doitchuu commented on src/plugin/code.js
> +    figma.notify(`이전 변경 사항이 선택 되었습니다.`);
P1: 개행 부탁드립니다 :) 

```suggestion
    }
    
    figma.notify(`이전 변경 사항이 선택 되었습니다.`);
```

2024-02-25 18:16 UTC, doitchuu commented on src/plugin/code.js
> +    figma.notify(`이전 변경 사항이 선택 되었습니다.`);
```suggestion
    figma.notify(`이전 변경 사항이 선택 되었습니다.`);
```
P1: 요 부분도 개행 부탁드립니다 :) 

```suggestion
    }
    
    figma.notify(`이전 변경 사항이 선택 되었습니다.`);
```

2024-02-25 18:16 UTC, doitchuu commented on src/plugin/code.js
> +    const isSelectedNode = figma.currentPage.selection[0];
P1: `isSelectedNode`는 값이 있는 지 없는지 bolean일 때 사용하는 게 좋은 것 같습니다.
현재는 초기값을 설정해주는 것이기 때문에 selectedNode 정도가 맞지 않을까 싶어요 :)

2024-02-25 18:16 UTC, doitchuu commented on src/plugin/code.js
> +    figma.notify(`이전 변경 사항이 선택 되었습니다.`);
P1: 요 부분은 저도 같은 생각입니다.

2024-02-25 18:16 UTC, doitchuu commented on src/plugin/code.js
> +    });
저희가 postMessage에 따라 type, content로 잘 나눠 주셨네요!! 👍

2024-02-25 18:16 UTC, doitchuu commented on src/ui/components/Difference/index.jsx
> +  const location = useLocation();
P1: 개행 부탁드립니다 : )

```suggestion
  });
  
  const location = useLocation();
```

2024-02-25 18:16 UTC, doitchuu commented on src/ui/components/Difference/index.jsx
>    });
P3: 현재 `useState`로 쓰이고 있는 상태가 많은데 관련 상태간 묶고 한번 개행해주는 건 어떨까요?

2024-02-25 18:16 UTC, doitchuu commented on src/ui/components/NewProject/index.jsx
> +        <form onSubmit={handleSubmitURI}>
꼼꼼하게 키보드 이벤트를 처리해주셨네요 💯

2024-02-25 18:16 UTC, doitchuu commented on src/ui/components/shared/Button.jsx
> +  tiny: css`
P2: tiny라는 말이 아주 작다는 의미긴 하지만 tiny 다음으로 작은 사항이나 small보다는 작지만 tiny보다 큰 버튼의 케이스가 나올 때 중간 단어를 찾기가 어려울 것 같아서 xs, xxs 처럼 `xsmall`이나 단위를 조금 더 직관적으로 사용할 수 있는 속성명은 어떠띾요?

2024-02-25 18:16 UTC, doitchuu commented on src/plugin/code.js
> +        (currentNodeIndex - 1) % differenceRectangleIdList.length;
P2: 해당 `-1`도 상수화 할 수 있지 않을까요?

2024-02-25 18:16 UTC, doitchuu commented on src/plugin/code.js
> +        (currentNodeIndex + 1) % differenceRectangleIdList.length;
P2: 해당 `+1`도 상수화 할 수 있지 않을까요?

2024-02-26 01:43 UTC, kyeongjun-ko commented on src/plugin/code.js
> +        (currentNodeIndex - 1) % differenceRectangleIdList.length;
differenceRectangleIdList.length를 한번씩 더 더해줘서 
0번째 인덱스에서 이전으로 갈 경우 -1이 아닌 마지막 인덱스가 선택 되도록 하였습니다.

기존 코드
```
const prevNodeIndex = currentNodeIndex - 1 % differenceRectangleIdList.length;
```
변경 코드
```
const prevNodeIndex = (currentNodeIndex - 1 + differenceRectangleIdList.length) % differenceRectangleIdList.length;
```

2024-02-26 02:10 UTC, kyeongjun-ko commented on src/ui/components/ProjectVersion/index.jsx
> +            frameCounts: Object.keys(diffingResult.content.differences).length,
변경 페이지에서 변경 사항이 있는경우 페이지네이션 정보를 set 해주기 때문에
서버에서 변경 영역을 렌더할때 정보를 보내주지 않아도 될것 같습니다. 👍 

사용되지 않는 코드를 확인하지 못했습니다. 바로 수정하겠습니다.

2024-02-26 02:40 UTC, kyeongjun-ko commented on src/plugin/code.js
> +    }
early return 을 적용하니 depth를 줄이고 가독성이 향상되었네요 👍

2024-02-26 02:45 UTC, kyeongjun-ko commented on src/ui/components/Difference/index.jsx
>    });
현재 state, store, location, query 네가지를 속성별로 구분짓기 위해서 개행하고 있는데
state에서도 상태별로 개행을 하게되면 상태를 속성별로 개행한 부분이 헷갈릴것같아요

2024-02-26 02:46 UTC, kyeongjun-ko commented on src/ui/components/shared/Button.jsx
> +  tiny: css`
tiny => xsmall 로 이름 변경하겠습니다.

2024-02-26 06:30 UTC, doitchuu commented on src/ui/components/Difference/index.jsx
> +    background-color: #868e96 !important;
`!important`를 안쓰고는 overwrite 안되었을까용..? 🥲

2024-02-26 06:39 UTC, doitchuu reviewed
코멘트 추가로 남겼습니다 :) 확인 부탁드립니다 👍

2024-02-26 06:39 UTC, doitchuu commented on src/ui/components/Difference/index.jsx
> +  .pagination-button-disable {
css 컨벤션도 반영 부탁드립니다 :)

2024-02-26 06:39 UTC, doitchuu commented on src/ui/components/shared/Button.jsx
> +  tiny: css`
요부분도 반영 부탁드립니다 👍  감사합니다!

2024-02-26 06:39 UTC, doitchuu commented on src/utils/formatTime.js
> +  const month = koreaTime.getMonth() + 1;
getMonth에 +1을 해주셨네요! 👍

2024-02-26 06:39 UTC, doitchuu commented on src/plugin/code.js
> +      if (message.content === "prev") {
P1: 개행 부탁드립니다.
```suggestion
      let nextIndex;
      
      if (message.content === "prev") {
```

2024-02-26 06:39 UTC, doitchuu commented on src/ui/components/Difference/index.jsx
>    });
네! 경준님 말씀이 맞는 것 같네요 👍

2024-02-26 06:39 UTC, doitchuu commented on src/ui/components/Difference/index.jsx
> +    background-color: #868e96 !important;
!important를 안하고 혹시 적용이 안되었을까요..?

2024-02-26 06:49 UTC, tjd985 requested changes
코멘트 확인 부탁드립니다!

2024-02-26 06:49 UTC, tjd985 commented on src/plugin/code.js
> +            differencesNumber) %
`currentIndex`가 `0`일 경우 `next`가 `-1`이 나오는 경우에 대비해서 `differencesNumber`를 더해주셨군요 👍 

- `P3`
변수명 
`differencesNumber`보다는 `differencesLength` 는 어떠세요?

2024-02-26 06:49 UTC, tjd985 commented on src/ui/components/shared/Button.jsx
> +  tiny: css`
반영이 안된 것 같슴다 👀

2024-02-26 06:49 UTC, tjd985 commented on src/utils/formatTime.js
> +  const month = koreaTime.getMonth() + 1;
수정해 주셨군요,,,🙇🏻‍♂️

2024-02-26 06:49 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +  }
반영이 안된 것 같습니다 👀

2024-02-26 06:49 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +  }, [clickedType]);
- `P2`
```suggestion
  useEffect(() => {
    if (clickedType.type === "prev") {
      postMessage("PAGINATION_BUTTON", "prev");
      
      return;
    }
    
    postMessage("PAGINATION_BUTTON", "next");
  }, [clickedType]);
```

2024-02-26 06:49 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +    }
- `P2`
`version`페이지에서 현재 페이지로 넘어올 경우에는
반드시 변경사항이 있지 않을까요?

어떤 의도로 작성해주신 것인지 설명 한번만 부탁드립니다! 😉

2024-02-26 06:49 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +  const [pagination, setPagination] = useState("");
- `P1`
이전 코멘트가 반영이 되지 않았습니다!

초깃값은 `""` 이지만, 실제로 set되는 데이터는 `object`
이에따른 초깃값 수정 입니다!

2024-02-26 06:49 UTC, tjd985 commented on src/plugin/code.js
> +    }
- `P1`
`else`문을 2개 작성하면 혹시 `syntax`에러가 안나나요?
만약, 안난다면 어떻게 동작하는지 궁금합니다

<img width="329" alt="image" src="https://github.com/Figci/Figci-Plugin-Client/assets/48385389/1cb6741f-2bc5-4e1a-abdf-a25c980b9a66">

2024-02-26 06:49 UTC, tjd985 commented on src/plugin/code.js
> +    }
```suggestion
    if (differencesNumber) {
      figma.ui.postMessage({
        type: "FRAME_PAGINATION",
        content: {
          result: true,
          currentCount: 0,
          frameCounts: differencesNumber,
        },
      });
      
      return;
    }
  
    figma.ui.postMessage({
      type: "FRAME_PAGINATION",
      content: {
        result: false,
        frameCounts: "- / -",
      },
    });
```

2024-02-26 08:12 UTC, kyeongjun-ko commented on src/ui/components/Difference/index.jsx
> +    }
비교 페이지 넘어올 경우 변경 사항이 있는지 여부를 알기 위해 작성했는데
비교 페이지 넘어올 경우 초기 마운트시 쿼리를 재호출해서 변경 결과를 받아서
변경 사항 여부를 판별해서 버전 활성화 하도록 로직 수정하였습니다.

2024-02-26 08:17 UTC, kyeongjun-ko commented on src/ui/components/Difference/index.jsx
> +  const [pagination, setPagination] = useState("");
실제로 set되는 데이터 형식에 맞춰 초깃값 설정했습니다.

2024-02-26 08:26 UTC, kyeongjun-ko commented on src/plugin/code.js
> +    }
따로 syntax 에러는 발생하지 않았고 반복되는 로직을 함수로 분리한뒤
early return 패턴 적용하여서 depth 를 줄여 리팩터링 하였습니다.

2024-02-26 08:46 UTC, kyeongjun-ko commented on src/plugin/code.js
> +            differencesNumber) %
네 좋습니다. Number는 의미가 너무 포괄적이라서
헷갈릴것같아서 반영하겠습니다.

2024-02-26 08:49 UTC, tjd985 reviewed
코멘트 확인 부탁드립니다!

2024-02-26 08:49 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +  justify-content: space-between;
- `P1`
위 두 속성은 붙혀주세요!

2024-02-26 09:00 UTC, doitchuu commented on src/plugin/code.js
> +      }
P2: else문 없이 사용해도 되지 않을까용..?

```suggestion
        nextIndex =
          (currentIndex + CONSTANTS.PAGINATION.INDEX_INCREASE) %
          differencesLength;
```

2024-02-26 09:00 UTC, kyeongjun-ko commented on src/ui/components/Difference/index.jsx
> +    background-color: #868e96 !important;
important 쓰지 않고 스타일 적용했습니다.

2024-02-26 09:01 UTC, doitchuu commented on src/ui/components/Difference/index.jsx
> +    min-width: 140px !important;
P1: width, height가 더 위로 올려주시면 좋을 것 같습니다 :) 
```suggestion
min-width: 140px !important;
border: 1px solid #adb5bd;
```

2024-02-26 09:02 UTC, doitchuu reviewed
리뷰 남겼습니다. 확인 부탁드립니다 :)

2024-02-26 09:02 UTC, kyeongjun-ko commented on src/plugin/code.js
> +      }
else 문이 없는 경우 이전버튼 선택시 위의 로직을 한번 실행하고
다음버튼일 경우의 아래의 로직을 한번 더 실행하기 때문에 사용했습니다.

2024-02-26 09:15 UTC, tjd985 requested changes

2024-02-26 09:15 UTC, tjd985 commented on src/ui/components/Difference/index.jsx
> +        return;
- `P1`
`if` 전에 개행 부탁드립니다! + `return` 전에 한줄 개행 부탁드립니다!

2024-02-26 09:25 UTC, doitchuu approved these changes
확인했습니다. 고생많으셨습니다 👍

2024-02-26 09:25 UTC, tjd985 approved these changes
수정사항 반영하시느라 고생 많으셨습니다!

2024-02-26 09:26 UTC, merged