Feat: Tooltip, Information 공용 컴포넌트 구현
Figci/Figci-Plugin-Client pull request #40
Opened 2024-04-24 17:27 UTC by doitchuu

## Fix (이슈 번호)
none

<br />

## 해결하려던 문제를 알려주세요!
Project URL 입력 페이지 내 Tooltip, Information 영역 렌더링 및 기능 구현이 필요했습니다.

<br />

## 어떻게 해결했나요?
`Tooltip`, `Information` 공용 컴포넌트를 추가했습니다.
해당 컴포넌트는 설명이 필요한 페이지 혹은 요소에 사용하기 위해(재사용) 공용 컴포넌트에 추가해두었습니다.
아래 반영된 내용 GIF와 이미지 참고 부탁드립니다.

<br />

## 잠깐! 확인해보셨나요?

- [X]  셀프 리뷰는 완료하셨나요?
- [X]  가장 최신 브랜치를 pull했나요?
- [X]  base 브랜치명을 확인하셨나요? (Front, Backend, feature 등)
- [X]  코드 컨벤션을 모두 지켰나요?
- [X]  적절한 라벨이 있나요?
- [X]  assignee가 있나요?

<br />

## Attachment(선택사항) 

### NewProject 컴포넌트 내 툴팁, 설명 영역 추가
![tooltip](https://github.com/Figci/Figci-Plugin-Client/assets/43771772/1de829a5-4885-494d-bfc0-a0d9a1061812)
<img width="932" alt="tooltip_1" src="https://github.com/Figci/Figci-Plugin-Client/assets/43771772/477be86a-1af2-4b8c-9cf3-b0fa54f7e71c">
<img width="913" alt="tooltip_2" src="https://github.com/Figci/Figci-Plugin-Client/assets/43771772/e8079f30-e907-4b82-b363-4494bbde4532">

<br />

2024-04-24 18:18 UTC, tjd985 requested changes
코멘트 확인 부탁드립니다!

2024-04-24 18:18 UTC, tjd985 commented on src/ui/components/shared/Tooltip.jsx
> +`;
- `P2`
css 네이밍 컨벤션에 맞게 수정해주시면 감사하겠습니다!!
<img width="275" alt="image" src="https://github.com/Figci/Figci-Plugin-Client/assets/48385389/e67e4656-dc7f-4313-8cf7-ee0dea7d9378">

2024-04-24 18:19 UTC, tjd985 approved these changes
확인했습니다!
고생하셨습니다!! 👍

2024-04-24 18:20 UTC, doitchuu commented on src/ui/components/shared/Tooltip.jsx
> +`;
이 부분을 놓쳤네요 👍  디테일한 확인 감사합니다 :)

2024-04-24 18:20 UTC, tjd985 approved these changes
수정사항 확인했습니다!
고생하셨습니다!! 👍

2024-04-25 03:45 UTC, kyeongjun-ko approved these changes
페이지네이션 코드 리팩터링 툴팁 컴포넌트 추가 확인했습니다 수고하셨습니다 🙏🏻

2024-04-25 03:45 UTC, kyeongjun-ko commented on src/plugin/code.js
> +const differenceRectangleList = [];
중복되는 의미의 id를 빼고 수정해주셨군요 👍

2024-04-25 03:45 UTC, kyeongjun-ko commented on src/plugin/code.js
> +    await focusScreen();
포커스 되지않는 케이스를 고려해서 비동기 처리 해주신걸까요?

2024-04-25 03:45 UTC, kyeongjun-ko commented on src/plugin/code.js
> +const isIncludeId = selectedNode => {
선택된 노드가 변경노드인지 확인하는 함수를 따로 분리해주셔서 코드 가독성이 훨씬 좋아졌네요 👍

2024-04-25 03:48 UTC, doitchuu commented on src/plugin/code.js
> +    await focusScreen();
배포로 인해서 비동기로 로직을 전체 변경해두었습니다 👍

2024-04-25 03:49 UTC, merged